apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: public-ip-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lior610/public-ip-app
    targetRevision: main
    path: helm/
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true