apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ default 2 .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "helm.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "helm.fullname" . }}
    spec:
      containers:
        - name: {{.Chart.Name }}
          image: '{{ required "Image repository is required!" .Values.image.repository }}:{{ default "stable" .Values.image.tag }}'
          ports:
            - containerPort: {{ .Values.service.port }}