replicaCount: 3

image:
  repository: lior610/public-ip
  tag: 20

service:
  enabled: true
  type: ClusterIP
  port: 5000
  targetPort: 5000

ingress:
  enabled: true
  hostname:
    enabled: false
  path: /
  servicePort: 5000
  className: nginx
