replicaCount: 3

image:
  repository: lior610/public-ip
  tag: 11

service:
  enabled: true
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30000

ingress:
  enabled: false
  hostname:
    enabled: false
  path: /
  servicePort: 5000
  className: nginx
