replicaCount: 3

readinessProbe:
  path: /
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 15
  periodSeconds: 20

resources:
  requests:
    cpu: 250m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi


image:
  repository: lior610/public-ip
  tag: 22

service:
  enabled: true
  type: ClusterIP
  port: 5000
  targetPort: 5000

ingress:
  enabled: true
  hostname:
    enabled: false
  path: /
  servicePort: 5000
  className: nginx
