name: CD Pipeline for public-ip app that deploys to argo-cd
on:
  workflow_run:
    workflows: ["CI Pipeline for public-ip app using flask and docker"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download image tag artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag

      - name: Read file tag
        id: read_tag
        run: |
          echo "IMAGE_TAG=$(cat image-tag.txt)" >> $GITHUB_OUTPUT

      - name: Update image tag and deploy to ArgoCD
        run: |
          sed -i "s/tag:.*/tag: ${{ steps.read_tag.outputs.IMAGE_TAG }}/" helm/values.yaml
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add helm/values.yaml
          git commit -m "Update image tag to ${{ steps.read_tag.outputs.IMAGE_TAG }} in helm/values.yaml"
          git push
          